### ISSUE TITLE
Running `meeshkan-tutorial` doesn't work. Running `meeshkan tutorial` does.

### ISSUE THREAD

**Issue by tesla809** [meeshkan/meeshkan-tutorial#11]
### Description
Running `meeshkan-tutorial` doesn't work.

### Steps to Reproduce
Followed instructions in meeshkan/meeshkan-tutorial.
I have Python 3.8 install on OSX and Python 3.7.6 via Anaconda.

1. Ran pip install meeshkan-tutorial
2. Created a new folder called /meeshkan in a directory.
3. Began the tutorial by invoking from the command line `meeshkan-tutorial`
4. Followed instructions until error.

**Note: The tutorial seems to work if I run it from meeshkan's main program.**
1. Run `meeshkan --help` to view commands
2. Run **`meeshkan tutorial`** to start the tutorial.
**This is different from running 'meeshkan-tutorial.**

**Expected behavior:**
What you expect to happen:
The tutorial will continue as planned

**Actual behavior:**
I get the error message:
```
Starting proxy◑Traceback (most recent call last):
  File "/usr/local/bin/meeshkan-tutorial", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/meeshkan_tutorial/tutorial.py", line 148, in cli
    starting_server('Starting proxy')
  File "/usr/local/lib/python3.8/site-packages/meeshkan_tutorial/tutorial.py", line 103, in starting_server
    raise Exception('Unable to start Meeshkan in 10 seconds. Please, check your environment.')
Exception: Unable to start Meeshkan in 10 seconds. Please, check your environment.
```

**Reproduces how often:**
What percentage of the time does it reproduce?
100% of the time tried.

### Versions
N/A

### Additional Information
I have Python 3.8 install on OSX and Python 3.7.6 via Anaconda.
Perhaps its an issue of where meeshkan-tutorial is installed?
It seems to work with regular meeshkan program.

**Comment by carolstran** [comment]
👋 @tesla809, thanks for reporting this bug! `meeshkan` and `meeshkan-tutorial` used to be two separate projects, but we recently ported the tutorial into the main `meeshkan` repo. Maybe that's what's causing the issue 🤔 What version of `meeshkan` are you using?

I tried reproducing it myself and I run into the same error when running `meeshkan-tutorial` at the starting proxy step. I wasn't able to run it using the `meeshkan tutorial` command (with the latest version, 0.2.25). However, I was able to run `meeshkan-tutorial` with only `meeshkan` installed, but ran into the same issue. Weird 🙎 

Tagging my colleagues @mikesol and @aby2s because they were recently fixing bugs in the tutorial and may have more insights!

**Comment by mikesol** [comment]
Hi @tesla809 , and thanks for reporting!
We will be deactivating this repo soon due to this error. `meeshkan tutorial` is the one that has its dependencies in-step because it is synced with `meeshkan`, whereas this one has some out-of-date dependencies.

**Comment by carolstran** [comment]
Ahhhh figured out why it wasn't running for me, local venv issue 🤦‍♀️  Anyway, like Mike said, we'll be archiving this repo and I'll update the `meeshkan` README and documentation to avoid this confusion in the future 😊
